use_frameworks!
platform :ios, '10.0'

target 'BadgifySwift_Example' do
  pod 'BadgifySwift', :path => '../'

  target 'BadgifySwift_Tests' do
    inherit! :search_paths

    pod 'iOSSnapshotTestCase' , '~> 6.0.3'
  end
end
