use_frameworks!
platform :ios, '9.0'

target 'BadgifySwift_Example' do
  pod 'BadgifySwift', :path => '../'

  target 'BadgifySwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
